cmake_minimum_required(VERSION 3.20)
# Dependency-free runner regression: all required suites, each omission, and
# an unrelated replacement that keeps the count at seven. Explicit MIN_TESTS=5
# must never weaken the name gate.
include(${CMAKE_CURRENT_LIST_DIR}/../cmake/McoExpectedUnitTests.cmake)
string(RANDOM LENGTH 8 _suffix)
set(_root "${CMAKE_CURRENT_BINARY_DIR}/required-suites-${_suffix}")
file(MAKE_DIRECTORY "${_root}")
set(_scenarios complete ${MCO_EXPECTED_UNIT_TESTS} replacement)
foreach(_scenario IN LISTS _scenarios)
    set(_names ${MCO_EXPECTED_UNIT_TESTS})
    if(_scenario STREQUAL "replacement")
        list(REMOVE_ITEM _names statement_fetch_test)
        list(APPEND _names unrelated_test)
    elseif(NOT _scenario STREQUAL "complete")
        list(REMOVE_ITEM _names ${_scenario})
    endif()
    set(_dir "${_root}/${_scenario}")
    file(MAKE_DIRECTORY "${_dir}")
    file(WRITE "${_dir}/CTestTestfile.cmake" "")
    foreach(_name IN LISTS _names)
        file(APPEND "${_dir}/CTestTestfile.cmake"
            "add_test(${_name} \"${CMAKE_COMMAND}\" -E true)\n")
    endforeach()
    execute_process(COMMAND ${CMAKE_COMMAND} "-DBUILD_DIR=${_dir}" -DMIN_TESTS=5
        -P "${CMAKE_CURRENT_LIST_DIR}/run_unit_tests.cmake"
        RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    if(_scenario STREQUAL "complete")
        if(NOT _rc EQUAL 0)
            message(FATAL_ERROR "Complete suite rejected: ${_out}${_err}")
        endif()
    else()
        if(_scenario STREQUAL "replacement")
            set(_missing statement_fetch_test)
        else()
            set(_missing ${_scenario})
        endif()
        if(_rc EQUAL 0 OR NOT _err MATCHES "required suite '${_missing}' is not registered")
            message(FATAL_ERROR "Missing suite not rejected correctly: ${_out}${_err}")
        endif()
    endif()
    message(STATUS "[required-suites] ${_scenario}: OK")
endforeach()
file(REMOVE_RECURSE "${_root}")
